export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const UNAUTH_USER = 'UNAUTH_USER';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const SAVE_LOCATION = 'SAVE_LOCATION';
export const FETCH_LOCATION = 'FETCH_LOCATION';
// export const SUBMIT_INTERESTS = 'SUBMIT_INTERESTS';
export const FETCH_WEATHER = 'FETCH_WEATHER';
export const STORE_INTERESTS = 'STORE_INTERESTS';

